server:
  port: 9090

management:
  security:
    enabled: false
  server:
    port: 9091

oneserver:
  advertiseIp: 0.0.0.0
  port: 10080
  selectorThreadsCount: 256

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

#logging:
#  level:
#    info.developerblog.spring.cloud.marathon.RibbonCustomConfiguration: DEBUG
#    com.netflix.loadbalancer.ZoneAffinityServerListFilter: DEBUG

logging.level.root: WARN

feign:
  hystrix:
    enabled: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.threadpool.default.coreSize: 500
hystrix.threadpool.default.maximumSize: 500

cool-app:
  ribbon:
#    ZonePattern: '.+\.(.+)'
#    ServerWeightTaskTimerInterval: 100
#    zoneAffinity.minAvailableServers: 1
    NFLoadBalancerPingInterval: 100
    ServerListRefreshInterval: 1000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    OkToRetryOnAllOperations: false
    EnableZoneAffinity: true

#niws.loadbalancer.cool-app.connectionFailureCountThreshold: 1
#niws.loadbalancer.cool-app.circuitTripTimeoutFactorSeconds: 15
#niws.loadbalancer.cool-app.circuitTripMaxTimeoutSeconds: 30

#niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit: 10

